name: Build Atuin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
defaults:
  run:
    shell: msys2 {0}
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
      
      # 修复点：添加 git 安装
      - run: pacman --noconfirm -Syu mingw-w64-ucrt-x86_64-rust mingw-w64-ucrt-x86_64-protobuf git
      
      - uses: Swatinem/rust-cache@v2
  #      - run: git clone https://github.com/atuinsh/atuin.git
      - run: cargo install --git https://github.com/atuinsh/atuin.git
      # - run: |
      #     cd atuin
      #     cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: atuin
          path: C:\Users\runneradmin\.cargo\bin\atuin.exe
