name: Build Atuin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # 每周日 UTC 时间午夜运行
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
      - name: 安装依赖
        run: pacman -Syu --noconfirm  mingw-w64-ucrt-x86_64-rust mingw-w64-ucrt-x86_64-protobuf
        
      - uses: Swatinem/rust-cache@v2

      - name: 克隆仓库并构建
        run: |
          git clone https://github.com/atuinsh/atuin.git
          cd atuin
          cargo build --release

      - name: 上传制品
        uses: actions/upload-artifact@v4
        with:
          name: atuin-bin
          path: atuin/target/release/atuin.exe
